[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools-git-versioning>=2.0,<3"
]
build-backend = "setuptools.build_meta"

[tool.distutils.bdist_wheel]
universal = true

[tool.setuptools-git-versioning]
enabled = true
dirty_template = "{tag}.post{ccount}+git.{sha}.dirty-{timestamp:%Y-%m-%dT%H-%M-%S}"

[project]
name = "ouroboros"
dynamic = ["version"]
dependencies = [
    "mambapy",
    "matplotlib",
    "torch",
    "tqdm",
    "transformers",
]

[project.optional-dependencies]
fast = [
    "causal-conv1d",
    "mamba-ssm",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
