[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools-git-versioning>=2.0,<3"
]
build-backend = "setuptools.build_meta"

[tool.distutils.bdist_wheel]
universal = true

[tool.setuptools-git-versioning]
enabled = true
dirty_template = "{tag}.post{ccount}+git.{sha}.dirty-{timestamp:%Y-%m-%dT%H-%M-%S}"

[project]
name = "ouroboros"
dynamic = ["version"]
dependencies = [
    "transformers",
    "accelerate",
    "datasets",
    "packaging",
    "mambapy",
    "mamba-ssm",
    "causal-conv1d"
]

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]  # ["."] by default